name: floating_bottom_navigation_bar
description: Highly customizable floating bottom navigation package for flutter.
version: 1.5.1
homepage: https://github.com/right7ctrl/flutter_floating_bottom_navigation_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:

  fonts:
    - family: Bold
      fonts:
        - asset: example/assets/fonts/gotham_narrow_bold.otf

    - family: Light
      fonts:
        - asset: example/assets/fonts/gotham_narrow_light.otf 